package nl.rubixstudios.billify.resourcepack;

import lombok.Getter;
import nl.rubixstudios.billify.Billify;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

/**
 * Glyph metrics of the Billify resource pack (generated by tools/resourcepack/generate.py).
 * The pack adds shifted copies of the vanilla font on private-use characters, one copy per
 * vertical offset ("dy"), so text can be drawn anywhere inside a menu title.
 */
public final class GuiFont {

    @Getter private static String packSha1 = "";

    private static int rowBase;
    private static int rowStride;
    private static final Map<Integer, Integer> ROWS = new HashMap<>();
    private static String charset = "";
    private static int[] advances = new int[0];
    private static final Map<String, int[]> GLYPHS = new HashMap<>();

    private GuiFont() {
    }

    public static void load() {
        final Properties properties = new Properties();
        try (InputStream in = Billify.getInstance().getResource("billify-font.properties")) {
            if (in == null) return;
            properties.load(new InputStreamReader(in, StandardCharsets.UTF_8));
        } catch (IOException ex) {
            Billify.getInstance().log("&cCould not load billify-font.properties: " + ex.getMessage());
            return;
        }

        packSha1 = properties.getProperty("pack.sha1", "");
        rowBase = Integer.parseInt(properties.getProperty("row.base"));
        rowStride = Integer.parseInt(properties.getProperty("row.stride"));

        final String[] dys = properties.getProperty("row.dys").split(",");
        for (int i = 0; i < dys.length; i++) {
            ROWS.put(Integer.parseInt(dys[i].trim()), i);
        }

        charset = properties.getProperty("charset");
        final String[] widths = properties.getProperty("advances").split(",");
        advances = new int[widths.length];
        for (int i = 0; i < widths.length; i++) {
            advances[i] = Integer.parseInt(widths[i].trim());
        }

        for (String key : properties.stringPropertyNames()) {
            if (!key.startsWith("glyph.")) continue;
            final String[] parts = properties.getProperty(key).split(",");
            GLYPHS.put(key.substring(6), new int[]{Integer.parseInt(parts[0]), Integer.parseInt(parts[1])});
        }
    }

    /** Index of a character in the shifted fonts, '?' for anything the pack does not cover. */
    private static int index(char c) {
        final int index = charset.indexOf(c);
        return index >= 0 ? index : charset.indexOf('?');
    }

    public static char shifted(char c, int dy) {
        if (dy == 0) return charset.indexOf(c) >= 0 ? c : '?';
        final Integer row = ROWS.get(dy);
        if (row == null) throw new IllegalArgumentException("No shifted font row for dy=" + dy);
        return (char) (rowBase + row * rowStride + index(c));
    }

    public static int advance(char c) {
        return advances[index(c)];
    }

    public static int width(String text) {
        int width = 0;
        for (char c : text.toCharArray()) width += advance(c);
        return width;
    }

    public static char glyph(String name) {
        return (char) GLYPHS.get(name)[0];
    }

    public static int glyphAdvance(String name) {
        return GLYPHS.get(name)[1];
    }
}
